# Generated by Django 5.0.6 on 2024-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
