# Generated by Django 5.0.6 on 2024-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
