# Generated by Django 5.0.6 on 2024-09-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='react',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
