# Generated by Django 5.0.6 on 2024-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_reaction_react_reaction_reaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='reaction',
            name='react',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
