# Generated by Django 5.0.6 on 2024-09-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_reaction_reaction_type_reaction_react'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='recipe',
        ),
    ]
