# Generated by Django 5.0.6 on 2024-09-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_comment_recipe_remove_reaction_recipe'),
        ('kitchen', '0005_remove_recipe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipe'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipe'),
        ),
    ]
