# Generated by Django 5.0.6 on 2024-10-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_recipe_reaction_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
