# Generated by Django 5.0.6 on 2024-09-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('promotions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotions')),
            ],
        ),
    ]
