# Generated by Django 5.0.6 on 2024-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_epsiode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisodepremium',
            name='description',
        ),
        migrations.RemoveField(
            model_name='podcastepisodepremium',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='podcastepisodepremium',
            name='episode_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
