# Generated by Django 5.0.6 on 2024-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premimumpodcast',
            name='subscription',
        ),
    ]
