# Generated by Django 5.0.6 on 2025-01-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterChef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_response', models.TextField()),
                ('HumanText', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='masterChef.humantext')),
            ],
        ),
    ]
