# Generated by Django 5.0.6 on 2025-01-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterChef', '0003_remove_savingresponse_humantext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingresponse',
            name='text',
        ),
        migrations.RemoveField(
            model_name='savingresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='savingresponse',
            name='HumanText',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterChef.humantext'),
        ),
    ]
