# Generated by Django 5.0.6 on 2025-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterChef', '0004_remove_savingresponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingresponse',
            name='HumanText',
        ),
        migrations.AddField(
            model_name='savingresponse',
            name='instance_human',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
