# Generated by Django 5.0.6 on 2024-09-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0006_alter_groupmessage_author_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatAPI.chatgroup'),
        ),
    ]
