# Generated by Django 5.0.6 on 2024-09-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0007_alter_groupmessage_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='author',
        ),
    ]
