# Generated by Django 5.0.6 on 2024-09-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0009_groupmessage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={},
        ),
    ]
