# Generated by Django 5.0.6 on 2024-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0010_alter_groupmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
