# Generated by Django 5.0.6 on 2024-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0011_profile_user_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
