# Generated by Django 5.0.6 on 2024-09-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ingredients', models.TextField()),
                ('flavour', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/kitchen/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('seasonal', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
