# Generated by Django 5.0.6 on 2024-09-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_comment_recipe_remove_reaction_recipe'),
        ('kitchen', '0003_remove_recipe_image_recipe_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.comment'),
        ),
    ]
