# Generated by Django 5.0.6 on 2024-09-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_recipe_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
    ]
