# Generated by Django 5.0.6 on 2024-09-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.reaction')),
            ],
        ),
    ]
