# Generated by Django 5.0.6 on 2024-09-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
        ('popularuty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularity',
            name='react_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.reaction'),
        ),
    ]
